name: flutter_plyr
description: simple plyr for play youtube inline. This is most stable and less control than other available packages.
version: 0.0.3
author: Faslu Rajan <rajafaslur@gmail.com>
homepage: https://github.com/faslurrajah/flutter_plyr

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


